import ProjectDescription

let workspace = Workspace(
  name: "App",
  projects: [
    "App",
    "Core",
    "Components",
    "Indigo",
    "FeatureA",
    "FeatureB",
  ],
  generationOptions: .options(
    autogeneratedWorkspaceSchemes: .disabled,
    lastXcodeUpgradeCheck: Version(16, 3, 0)
  )
)
